title: Laiba Hamid
logo: ![image](https://github.com/Laibahmmd/Laibahmmd.github.io/assets/146424732/19257c49-aa8b-47c4-ad1b-4d12f25722e2)
description: Computer Science Portfolio
#show_downloads: true
theme: jekyll-theme-minimal
